import { EAUBaseValidator } from "eau-core";
import { DocumentFormValidationContext, PoliceDepartmentValidator } from "eau-documents";
import { ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVM } from "../models/ModelsAutoGenerated";

export class ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVMValidator extends EAUBaseValidator<ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.issuingPoliceDepartment).setValidator(new PoliceDepartmentValidator());
    }
}