import { EAUBaseValidator, ErrMsgCodesConstants, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext } from "eau-documents";
import { ApplicationForIssuingDocumentofVehicleOwnershipDataVM } from "../models/ModelsAutoGenerated";
import { ApplicationForIssuingDocumentofVehicleOwnershipDataRegistrationAndMakeVMValidator } from "./ApplicationForIssuingDocumentofVehicleOwnershipDataRegistrationAndMakeVMValidator";

export class ApplicationForIssuingDocumentofVehicleOwnershipDataVMValidator extends EAUBaseValidator<ApplicationForIssuingDocumentofVehicleOwnershipDataVM, DocumentFormValidationContext> {
    constructor() {
        super();
        
        this.ruleFor(m => m.registrationAndMake).setValidator(new ApplicationForIssuingDocumentofVehicleOwnershipDataRegistrationAndMakeVMValidator());

        this.ruleFor(m => m.ownershipCertificateReason).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new ApplicationForIssuingDocumentofVehicleOwnershipDataVM(), 'ownershipCertificateReason'));            
    }
}