import { EAUBaseValidator, resourceManager } from "eau-core";
import { DocumentFormValidationContext } from "eau-documents";
import { VehicleRegistrationChangeVM } from "../models/ModelsAutoGenerated";
import { VehicleOwnerDataVMValidator } from "./VehicleOwnerDataVMValidator";
import { VehicleBuyerDataVMValidator } from "./VehicleBuyerDataVMValidator";
import { VehicleRegistrationDataValidator } from "./VehicleRegistrationDataValidator";
import { action } from "mobx";

export class ChangeRegistrationWithPersonOrEntityValidator extends EAUBaseValidator<VehicleRegistrationChangeVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.vehicleRegistrationData).setCollectionValidator(new VehicleRegistrationDataValidator());

        this.ruleFor(m => m.currentOwners).setCollectionValidator(new VehicleOwnerDataVMValidator());

        this.ruleFor(m => m.newOwners).setCollectionValidator(new VehicleBuyerDataVMValidator());
    }

    @action validate(obj: VehicleRegistrationChangeVM): boolean {
        let result = super.validate(obj);

        if (obj.vehicleRegistrationData && obj.vehicleRegistrationData.length > 1) {
            if (obj.vehicleRegistrationData.length != obj.vehicleRegistrationData.map(item => item.registrationNumber).filter((v, i, s) => s.indexOf(v) === i).length)
            {
                //В полето за идентификационни данни за ППС има дублиран регистрационен номер на ППС
                obj.addError(resourceManager.getResourceByKey("DOC_GL_DUPLICATE_REGNUMBER_E"));
                result = false;
            }
        }

        return result;
    }
}