import { EAUBaseValidator, ErrMsgCodesConstants, ResourceHelpers, resourceManager } from "eau-core";
import { DocumentFormValidationContext, EkatteAddressValidator } from "eau-documents";
import { MerchantData } from "../models/ModelsAutoGenerated";

export class MerchantDataValidator extends EAUBaseValidator<MerchantData, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.entityManagementAddress).setValidator(new EkatteAddressValidator());

        this.ruleFor(m => m.correspondingAddress).setValidator(new EkatteAddressValidator());

        this.ruleFor(m => m.phone).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new MerchantData(), 'phone'));

        this.ruleFor(m => m.phone).isValidPhone().withMessage(resourceManager.getResourceByKey("DOC_GL_WRONG_PHONE_NUMBER_E"))
    }
}