import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent, ResourceHelpers, attributesClassFormControlLabel, ValidationSummary, ValidationSummaryStrategy } from "eau-core";
import React from "react";
import { IssuedBulgarianIdentityDocumentInfo, BulgarianIdentityDocumentTypes } from "../../models/ModelsAutoGenerated";
import { withCollectionItems } from "eau-documents";

export class IssuedBulgarianIdentityDocumentInfoUIImpl extends EAUBaseComponent<BaseProps, IssuedBulgarianIdentityDocumentInfo> {

    renderEdit(): JSX.Element {
        return (
            <>
                <ValidationSummary model={this.model} strategy={ValidationSummaryStrategy.includeOnlyModelErrors} />
                <div className="row">
                    <div className="form-group col-sm-6 col-md-4">
                        {this.labelFor(x => x.issuingYear, "DOC_BDS_BulgarianIdentityDocumentNumber_YearofissueConnectedWithIssuedBulgarianIdentityDocuments_L", attributesClassFormControlLabel)}
                        {this.textBoxFor(x => x.issuingYear)}
                    </div>

                    <div className="form-group col-sm-6 col-md-4">
                        {this.labelFor(x => x.docType, "DOC_BDS_BulgarianIdentityDocumentNumber_TypeofdocumentConnectedWithIssuedBulgarianIdentityDocuments_L", attributesClassFormControlLabel)}
                        {this.dropDownListFor(m => m.docType, ResourceHelpers.getSelectListItemsForEnum(BulgarianIdentityDocumentTypes), null, null, true, this.getResource('GL_CHOICE_L'))}
                    </div>
                </div>
            </>
        )
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <ValidationSummary model={this.model} strategy={ValidationSummaryStrategy.includeOnlyModelErrors} />
                <div className="row">
                    <div className="form-group col-sm-6 col-md-4">
                        <h4 className="form-control-label">{this.getResource("DOC_BDS_BulgarianIdentityDocumentNumber_YearofissueConnectedWithIssuedBulgarianIdentityDocuments_L")}</h4>
                        {this.textDisplayFor(x => x.issuingYear)}
                    </div>
                    <div className="form-group col-sm-6 col-md-4">
                        <h4 className="form-control-label">{this.getResource("DOC_BDS_BulgarianIdentityDocumentNumber_TypeofdocumentConnectedWithIssuedBulgarianIdentityDocuments_L")}</h4>
                        {ResourceHelpers.getResourceByEmun(this.model.docType, BulgarianIdentityDocumentTypes)}
                    </div>
                </div>
            </>
        )
    }
}

export const IssuedBulgarianIdentityDocumentInfoUI = withCollectionItems(IssuedBulgarianIdentityDocumentInfoUIImpl, {
    initItem: () => new IssuedBulgarianIdentityDocumentInfo(),
    addButtonLabelKey: 'DOC_BDS_BulgarianIdentityDocuments_YearandTypeConnectedWithIssuedBulgarianIdentityDocuments_L'
})