import { EAUBaseValidator } from "eau-core";
import { DocumentFormValidationContext, ElectronicServiceApplicantVMValidator } from "eau-documents";
import { ApplicationForWithdrawServiceVM } from "../../models/ModelsAutoGenerated";
import { ApplicationForWithdrawServiceDataValidator } from "../ApplicationForWithdrawServiceDataValidator";

export class ApplicationForWithdrawServiceValidator
    extends EAUBaseValidator<ApplicationForWithdrawServiceVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new ApplicationForWithdrawServiceDataValidator());
    }
}