import { BaseProps } from "cnsys-ui-react";
import { attributesClassFormControlLabel, attributesClassFormControlReqired, attributesClassFormControlRequiredLabel, EAUBaseComponent } from "eau-core";
import React from "react";
import { Ammunition } from "../../models/ModelsAutoGenerated";


export class AmmunitionUI extends EAUBaseComponent<BaseProps, Ammunition> {

    renderEdit() {
        return (
            <>
                <div className="row">
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.tradeName, null, attributesClassFormControlLabel)}
                        {this.textBoxFor(x => x.tradeName)}
                    </div>
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.numberOON, null, attributesClassFormControlLabel)}
                        {this.textBoxFor(x => x.numberOON)}
                    </div>
                </div>
                <div className="row">
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.caliber, null, attributesClassFormControlLabel)}
                        {this.textBoxFor(x => x.caliber)}
                    </div>
                    <div className="form-group col-sm-6">
                        {this.labelFor(x => x.count, null, attributesClassFormControlRequiredLabel)}
                        {this.textBoxFor(x => x.count, attributesClassFormControlReqired)}
                    </div>
                </div>
            </>
        );
    }

    renderDisplay() {
        return (
            <>
                <div className="row">
                    <div className="form-group col-sm-6">
                        <h4 className="form-control-label">{this.getResourceByProperty(x => x.tradeName)}</h4>
                        {this.textDisplayFor(x => x.tradeName)}
                    </div>
                    <div className="form-group col-sm-6">
                        <h4 className="form-control-label">{this.getResourceByProperty(x => x.numberOON)}</h4>
                        {this.textDisplayFor(x => x.numberOON)}
                    </div>
                </div>
                <div className="row">
                    <div className="form-group col-sm-6">
                        <h4 className="form-control-label">{this.getResourceByProperty(x => x.caliber)}</h4>
                        {this.textDisplayFor(x => x.caliber)}
                    </div>
                    <div className="form-group col-sm-6">
                        <h4 className="form-control-label">{this.getResourceByProperty(x => x.count)}</h4>
                        {this.textDisplayFor(x => x.count)}
                    </div>
                </div>
            </>
        );
    };
}