import { EAUBaseValidator, ResourceHelpers, resourceManager, ErrMsgCodesConstants } from "eau-core";
import { DocumentFormValidationContext } from "eau-documents";
import { ForeignIdentityBasicDataVM } from "../models/ModelsAutoGenerated";

export class ForeignIdentityBasicDataValidator extends EAUBaseValidator<ForeignIdentityBasicDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.phone).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new ForeignIdentityBasicDataVM(), 'phone'))
        this.ruleFor(m => m.phone).isValidPhone().withMessage(resourceManager.getResourceByKey("DOC_GL_WRONG_PHONE_NUMBER_E"))
    }
}