import { BaseProps } from 'cnsys-ui-react';
import { resourceManager } from 'eau-core';
import React from 'react';
import { LDAPUser } from '../../../models/ModelsAutoGenerated';

interface LDAPUsersProfilesResultsProps extends BaseProps {
    userProfiles: LDAPUser[];
    onGetUser?: (user) => void;
}

const LDAPUsersProfilesResultsUI: React.FC<LDAPUsersProfilesResultsProps> = ({ userProfiles, onGetUser }) => {

    const onSelectUser = (user) => {
        onGetUser(user);
    }

    return <div className="table-responsive">
        <table className="table table-bordered table-striped table-hover">
            <thead>
                <tr>
                    <th></th>
                    <th>{resourceManager.getResourceByKey("GL_USERNAME_L")}</th>
                    <th>{resourceManager.getResourceByKey("GL_EMPLOYEE_L")}</th>
                    <th>{resourceManager.getResourceByKey("GL_EMAIL_L")}</th>
                </tr>
            </thead>
            <tbody id="content">
                {
                    userProfiles.map((user, index) => {
                        return <tr key={user.accountGuid}>
                            <td className="single-icon-td">
                                <div className="custom-control custom-radio">
                                    <input className="custom-control-input" type="radio" name="ldapUser" value="ldapUser" id={`ldapUser-${index}`} onChange={() => onSelectUser(user)} />
                                    <label className="custom-control-label" htmlFor={`ldapUser-${index}`}></label>
                                </div>
                            </td>
                            <td>{user.username}</td>
                            <td>{`${user.firstName} ${user.lastName}`}</td>
                            <td>{user.email}</td>
                        </tr>
                    })
                }
            </tbody>
        </table>
    </div>
}

export default LDAPUsersProfilesResultsUI;