import * as React from "react";
import { observer } from "mobx-react";
import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent, ResourceHelpers } from "eau-core";
import { RequestForApplyingForServiceForIssuingOfBCICardOrPassportDataVM } from "../../models/ModelsAutoGenerated";
import { FieldFormUI, IdentityDocumentType } from "eau-documents";


interface RequestForApplyingForServiceForIssuingOfBulgarianCitizensIdentityCardOrPassportDataUIProps extends BaseProps {
}


@observer
export class RequestForApplyingForServiceForIssuingOfBulgarianCitizensIdentityCardOrPassportDataUI
    extends EAUBaseComponent<RequestForApplyingForServiceForIssuingOfBulgarianCitizensIdentityCardOrPassportDataUIProps, RequestForApplyingForServiceForIssuingOfBCICardOrPassportDataVM> {

    constructor(props: RequestForApplyingForServiceForIssuingOfBulgarianCitizensIdentityCardOrPassportDataUIProps) {
        super(props);

    }

    renderEdit(): JSX.Element {
        return (
            <>

            </>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>


                <FieldFormUI title={this.getResourceByProperty(m => m)}>
                    {this.model.identificationDocuments && this.model.identificationDocuments.length > 0 ?
                        <ul className="list-filed">
                            {
                                this.model.identificationDocuments.map((item: IdentityDocumentType, index: number) => {
                                    return (
                                        <div className="row">
                                            <div className="form-group col-12">
                                                <h4 className="form-control-label">{this.getResourceByProperty(m => m.identificationDocuments)}</h4>
                                                {ResourceHelpers.getResourceByEmun(item, IdentityDocumentType)}
                                            </div>
                                        </div>
                                    )
                                })
                            }
                        </ul>
                        : null
                    }
                </FieldFormUI>
            </>
        );
    }
}