import { EAUBaseValidator } from "eau-core";
import { DeclarationsVMValidator, DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsVM } from "../../models/ModelsAutoGenerated";
import { ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsDataVMValidator } from '../ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsDataVMValidator';
import { MerchantDataValidator } from "../MerchantDataValidator";

export class ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsValidator extends EAUBaseValidator<ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new ApplicationForIssuingOfTemporaryRegistrationPlatesToMerchantsDataVMValidator());
        this.ruleFor(m => m.merchantData).setValidator(new MerchantDataValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}