import { EAUBaseValidator } from "eau-core";
import { ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesVM } from "../../models/ModelsAutoGenerated";
import { DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, DeclarationsVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVMValidator } from '../ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVMValidator'

export class ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesValidator extends EAUBaseValidator<ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new ApplicationForIssuingOfControlCouponForDriverWithNoPenaltiesDataVMValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}