import { EAUBaseValidator } from "eau-core";
import { ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponVM } from "../../models/ModelsAutoGenerated";
import { DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, DeclarationsVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponDataVMValidator } from '../ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponDataVMValidator'

export class ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponValidator extends EAUBaseValidator<ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new ApplicationForIssuingOfDuplicateOfDrivingLicenseControlCouponDataVMValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}