import { EAUBaseValidator } from "eau-core";
import { DeclarationsVMValidator, DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { ApplicationForCommissioningTemporarilySuspendedVehicleVM } from "../../models/ModelsAutoGenerated";
import { VehicleDataRequestValidator } from '../VehicleDataRequestValidator';

export class ApplicationForCommissioningTemporarilySuspendedVehicleValidator extends EAUBaseValidator<ApplicationForCommissioningTemporarilySuspendedVehicleVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new VehicleDataRequestValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}