import { EAUBaseValidator } from "eau-core";
import { CertificateOfVehicleOwnershipVM } from "../../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "eau-documents";

export class CertificateOfVehicleOwnershipValidator extends EAUBaseValidator<CertificateOfVehicleOwnershipVM, DocumentFormValidationContext> {
    constructor() {
        super();

    }
}