import { EAUBaseValidator } from "eau-core";
import { DocumentFormValidationContext } from "eau-documents";
import { ReportForVehicleVM } from "../../models/ModelsAutoGenerated";

export class ReportForVehicleValidator extends EAUBaseValidator<ReportForVehicleVM, DocumentFormValidationContext> {
    constructor() {
        super();

    }
}