import { DocumentFormValidationContext, Section, DocumentFormManagerBase } from 'eau-documents'
import { ResourceHelpers } from 'eau-core';
import { CertificateToWorkWithFluorinatedGreenhouseGassesVM } from '../models/ModelsAutoGenerated';
import { CertificateToWorkWithFluorinatedGreenhouseGassesValidator } from '../validations/forms/CertificateToWorkWithFluorinatedGreenhouseGassesValidator';
import { CertificateToWorkWithFluorinatedGreenhouseGassesUI } from '../ui/certificate-forms/CertificateToWorkWithFluorinatedGreenhouseGassesUI';


export class CertificateToWorkWithFluorinatedGreenhouseGassesManager extends DocumentFormManagerBase<CertificateToWorkWithFluorinatedGreenhouseGassesVM>{

    //#region ApplicationFormManagerBase

    createDocument(obj: any): CertificateToWorkWithFluorinatedGreenhouseGassesVM {
        return new CertificateToWorkWithFluorinatedGreenhouseGassesVM(obj);
    }

    //#endregion   

    protected createSections(validationContext: DocumentFormValidationContext): Section[] {
        var sections = super.createSections(validationContext);

        var main = new Section();
        main.code = "main";
        main.title = ResourceHelpers.getResourceByProperty(m => m, CertificateToWorkWithFluorinatedGreenhouseGassesVM);
        main.form = this.documentForm;
        main.formUICmp = CertificateToWorkWithFluorinatedGreenhouseGassesUI;
        main.validator = new CertificateToWorkWithFluorinatedGreenhouseGassesValidator();
        main.validator.setValidationContext(validationContext);
        main.validate = () => this.validateSection(main);

        sections.push(main);

        return sections;
    }
}