import { EAUBaseValidator, ErrMsgCodesConstants, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, PersonalInformationValidator, PoliceDepartmentValidator } from "eau-documents";
import { NotificationForFirearmDataVM } from "../models/ModelsAutoGenerated";
import { TechnicalSpecificationOfWeaponValidator } from "./TechnicalSpecificationOfWeaponValidator";

export class NotificationForFirearmDataValidator extends EAUBaseValidator<NotificationForFirearmDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.issuingPoliceDepartment).setValidator(new PoliceDepartmentValidator());
        this.ruleFor(m => m.applicantInformation).setValidator(new PersonalInformationValidator());
        this.ruleFor(m => m.technicalSpecificationsOfWeapons).setCollectionValidator(new TechnicalSpecificationOfWeaponValidator());
        this.ruleFor(m => m.purchaserUIC).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new NotificationForFirearmDataVM(), 'purchaserUIC'));

        this.ruleFor(m => m.purchaserUIC).isValidBULSTAT()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.InvalidBULSTATAndEIK, new NotificationForFirearmDataVM(), 'purchaserUIC'));
    }
}