import { EAUBaseValidator, ErrMsgCodesConstants, ResourceHelpers } from "eau-core";
import { DocumentFormValidationContext, PersonalInformationValidator, PoliceDepartmentValidator } from "eau-documents";
import { NotificationForNonFirearmDataVM, WeaponNoticeType } from "../models/ModelsAutoGenerated";
import { TechnicalSpecificationOfWeaponValidator } from "./TechnicalSpecificationOfWeaponValidator";

export class NotificationForNonFirearmDataValidator extends EAUBaseValidator<NotificationForNonFirearmDataVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.issuingPoliceDepartment).setValidator(new PoliceDepartmentValidator());
        this.ruleFor(m => m.applicantInformation).setValidator(new PersonalInformationValidator());
        this.ruleFor(m => m.technicalSpecificationsOfWeapons).setCollectionValidator(new TechnicalSpecificationOfWeaponValidator());
        this.ruleFor(x => x.purchaserInformation).notEmpty().when(x => x.weaponNoticeType == WeaponNoticeType.Transferred || x.weaponNoticeType == WeaponNoticeType.SaleDonation)
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new NotificationForNonFirearmDataVM(), 'purchaserInformation'));
    }
}