import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent } from "eau-core";
import { observer } from "mobx-react";
import React from "react";
import { GenderData } from "../../models/ModelsAutoGenerated";

@observer export class GenderDataUI extends EAUBaseComponent<BaseProps, GenderData> {

    renderEdit(): JSX.Element {
        return (
            <div className="form-group col-sm-4">
                <h4 className="form-control-label">{this.getResourceByProperty(m => m)}</h4>
                <p className="field-text">{this.getGenderText()}</p>
            </div>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <div className="form-group col-sm-4">
                <h4 className="form-control-label">{this.getResourceByProperty(m => m)}</h4>
                <p className="field-text">{this.getGenderText()}</p>
            </div>
        );
    }

    getGenderText() {
        if (this.model.genders && this.model.genders.length > 0) {
            if (this.model.genders[0].name.toUpperCase() == "MALE")
                return this.getResource("DOC_GL_MALE_L");
            if (this.model.genders[0].name.toUpperCase() == "FEMALE")
                return this.getResource("DOC_GL_FEMALE_L");
        }
        return null;
    }

}