import { EAUBaseValidator } from "eau-core";
import { DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, DeclarationsVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { ApplicationForIssuingDocumentForForeignersVM } from "../../models/ModelsAutoGenerated";
import { ApplicationForIssuingDocumentForForeignersDataVMValidator } from "../ApplicationForIssuingDocumentForForeignersDataVMValidator";


export class ApplicationForIssuingDocumentForForeignersValidator extends EAUBaseValidator<ApplicationForIssuingDocumentForForeignersVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new ApplicationForIssuingDocumentForForeignersDataVMValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}