import { EAUBaseValidator } from "eau-core";
import { AuthorWithQualityVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";
import { ElectronicStatementAuthorVMValidator } from "./ElectronicStatementAuthorVMValidator";

export class AuthorWithQualityVMValidator extends EAUBaseValidator<AuthorWithQualityVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.author).setValidator(new ElectronicStatementAuthorVMValidator());
    }
}