import { EAUBaseValidator } from "eau-core";
import { ElectronicServiceApplicantVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";
import { RecipientGroupVMValidator } from "./RecipientGroupVMValidator";

export class ElectronicServiceApplicantVMValidator extends EAUBaseValidator<ElectronicServiceApplicantVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.recipientGroup).setValidator(new RecipientGroupVMValidator());
    }
}