import { EAUBaseValidator } from "eau-core";
import { ElectronicServiceRecipientVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";
import { PersonBasicDataVMValidator } from "./PersonBasicDataVMValidator";
import { EntityBasicDataValidator } from "./EntityBasicDataValidator";

export class ElectronicServiceRecipientVMValidator extends EAUBaseValidator<ElectronicServiceRecipientVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.itemPersonBasicData).setValidator(new PersonBasicDataVMValidator());
        //this.ruleFor(m => m.itemForeignCitizenBasicData).setValidator(new ForeignCitizenBasicDataValidator());
        this.ruleFor(m => m.itemEntityBasicData).setValidator(new EntityBasicDataValidator());
        //this.ruleFor(m => m.itemForeignEntityBasicData).setValidator(new ForeignEntityBasicDataVMValidator());
    }
}