import { EAUBaseValidator, ResourceHelpers, ErrMsgCodesConstants } from "eau-core";
import { IssuerCountryVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";

export class IssuerCountryValidator extends EAUBaseValidator<IssuerCountryVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.countryName).notEmpty().withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new IssuerCountryVM(), 'countryGRAOCode'));
    }
}