import { EAUBaseValidator, ResourceHelpers, ErrMsgCodesConstants } from "eau-core";
import { PersonDataExtendedVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";

export class PersonDataExtendedValidator extends EAUBaseValidator<PersonDataExtendedVM, DocumentFormValidationContext> {

    constructor() {
        super();

        this.ruleFor(m => m.eyesColor).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataExtendedVM(), 'eyesColor'))
        this.ruleFor(m => m.height).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataExtendedVM(), 'height'))
        this.ruleFor(m => m.maritalStatus).notEmpty()
            .withMessage(ResourceHelpers.formatErrorMessage(ErrMsgCodesConstants.DefaultNotEmptyErrorMessage, new PersonDataExtendedVM(), 'maritalStatus'))
    }
}