import { EAUBaseValidator } from "eau-core";
import { TravelDocumentVM } from "../models/ModelsAutoGenerated";
import { DocumentFormValidationContext } from "./DocumentFormValidationContext";

export class TravelDocumentValidator extends EAUBaseValidator<TravelDocumentVM, DocumentFormValidationContext> {

  
}