import { DocumentFormValidationContext, Section, DocumentFormManagerBase } from 'eau-documents'
import { ResourceHelpers } from 'eau-core';
import { CertificateOfVehicleOwnershipVM } from '../models/ModelsAutoGenerated';
import { CertificateOfVehicleOwnershipValidator } from '../validations/forms/CertificateOfVehicleOwnershipValidator';
import { CertificateOfVehicleOwnershipUI } from '../ui/certificate-forms/CertificateOfVehicleOwnershipUI';

export class CertificateOfVehicleOwnershipManager extends DocumentFormManagerBase<CertificateOfVehicleOwnershipVM>{

    //#region ApplicationFormManagerBase

    createDocument(obj: any): CertificateOfVehicleOwnershipVM {
        return new CertificateOfVehicleOwnershipVM(obj);
    }

    //#endregion   

    protected createSections(validationContext: DocumentFormValidationContext): Section[] {
        var sections = super.createSections(validationContext);

        var main = new Section();
        main.code = "main";
        main.title = ResourceHelpers.getResourceByProperty(m => m, CertificateOfVehicleOwnershipVM);
        main.form = this.documentForm;
        main.formUICmp = CertificateOfVehicleOwnershipUI;
        main.validator = new CertificateOfVehicleOwnershipValidator();
        main.validator.setValidationContext(validationContext);
        main.validate = () => this.validateSection(main);

        sections.push(main);

        return sections;
    }   
}