import { DocumentFormValidationContext, Section, DocumentFormManagerBase } from 'eau-documents'
import { ResourceHelpers } from 'eau-core';
import { NotificationForTemporaryRegistrationPlatesVM } from '../models/ModelsAutoGenerated';
import { NotificationForTemporaryRegistrationPlatesValidator } from '../validations/forms/NotificationForTemporaryRegistrationPlatesValidator';
import { NotificationForTemporaryRegistrationPlatesUI } from '../ui/certificate-forms/NotificationForTemporaryRegistrationPlatesUI';

export class NotificationForTemporaryRegistrationPlatesManager extends DocumentFormManagerBase<NotificationForTemporaryRegistrationPlatesVM>{

    //#region ApplicationFormManagerBase

    createDocument(obj: any): NotificationForTemporaryRegistrationPlatesVM {
        return new NotificationForTemporaryRegistrationPlatesVM(obj);
    }

    //#endregion   

    protected createSections(validationContext: DocumentFormValidationContext): Section[] {
        var sections = super.createSections(validationContext);

        var main = new Section();
        main.code = "main";
        main.title = ResourceHelpers.getResourceByProperty(m => m, NotificationForTemporaryRegistrationPlatesVM);
        main.form = this.documentForm;
        main.formUICmp = NotificationForTemporaryRegistrationPlatesUI;
        main.validator = new NotificationForTemporaryRegistrationPlatesValidator();
        main.validator.setValidationContext(validationContext);
        main.validate = () => this.validateSection(main);

        sections.push(main);

        return sections;
    }   
}