import { DocumentFormValidationContext, Section, DocumentFormManagerBase } from 'eau-documents'
import { ResourceHelpers } from 'eau-core';
import { ReportForChangingOwnershipVM } from '../models/ModelsAutoGenerated';
import { ReportForChangingOwnershipValidator } from '../validations/forms/ReportForChangingOwnershipValidator';
import { ReportForChangingOwnershipUI } from '../ui/certificate-forms';
 
export class ReportForChangingOwnershipManager extends DocumentFormManagerBase<ReportForChangingOwnershipVM>{

    //#region ApplicationFormManagerBase

    createDocument(obj: any): ReportForChangingOwnershipVM {
        return new ReportForChangingOwnershipVM(obj);
    }

    //#endregion   

    protected createSections(validationContext: DocumentFormValidationContext): Section[] {
        var sections = super.createSections(validationContext);

        var main = new Section();
        main.code = "main";
        main.title = ResourceHelpers.getResourceByProperty(m => m, ReportForChangingOwnershipVM);
        main.form = this.documentForm;
        main.formUICmp = ReportForChangingOwnershipUI;
        main.validator = new ReportForChangingOwnershipValidator();
        main.validator.setValidationContext(validationContext);
        main.validate = () => this.validateSection(main);

        sections.push(main);

        return sections;
    }
}