import moment from 'moment'
import { observable } from 'mobx'
import { TypeSystem, BaseDataModel, BasePagedSearchCriteria } from 'cnsys-core'
import { moduleContext } from '../ModuleContext'
import { Functionalities } from 'eau-core'
import { ObjectTypes, ActionTypes } from './ModelsAutoGenerated';


@TypeSystem.typeDecorator('LogAction', moduleContext.moduleName)
export class LogAction extends BaseDataModel {

    //#region logActionID

    @observable private _logActionID: number = null;

    @TypeSystem.propertyDecorator('number')
    public set logActionID(val: number) {
        this._logActionID = val;
    }

    public get logActionID(): number {
        return this._logActionID;
    }

    //#endregion logActionID 

    //#region logActionDate

    @observable private _logActionDate: moment.Moment = null;

    @TypeSystem.propertyDecorator('moment')
    public set logActionDate(val: moment.Moment) {
        this._logActionDate = val;
    }

    public get logActionDate(): moment.Moment {
        return this._logActionDate;
    }

    //#endregion logActionDate 

    //#region objectType

    @observable private _objectType: ObjectTypes = null;

    @TypeSystem.propertyDecorator(ObjectTypes)
    public set objectType(val: ObjectTypes) {
        this._objectType = val;
    }

    public get objectType(): ObjectTypes {
        return this._objectType;
    }

    //#endregion objectType 

    //#region actionType

    @observable private _actionType: ActionTypes = null;

    @TypeSystem.propertyDecorator(ActionTypes)
    public set actionType(val: ActionTypes) {
        this._actionType = val;
    }

    public get actionType(): ActionTypes {
        return this._actionType;
    }

    //#endregion actionType 

    //#region functionality

    @observable private _functionality: Functionalities = null;

    @TypeSystem.propertyDecorator(Functionalities)
    public set functionality(val: Functionalities) {
        this._functionality = val;
    }

    public get functionality(): Functionalities {
        return this._functionality;
    }

    //#endregion functionality 

    //#region key

    @observable private _key: string = null;

    @TypeSystem.propertyDecorator('string')
    public set key(val: string) {
        this._key = val;
    }

    public get key(): string {
        return this._key;
    }

    //#endregion key 

    //#region loginSessionID

    @observable private _loginSessionID: string = null;

    @TypeSystem.propertyDecorator('string')
    public set loginSessionID(val: string) {
        this._loginSessionID = val;
    }

    public get loginSessionID(): string {
        return this._loginSessionID;
    }

    //#endregion loginSessionID 

    //#region userID

    @observable private _userID: number = null;

    @TypeSystem.propertyDecorator('number')
    public set userID(val: number) {
        this._userID = val;
    }

    public get userID(): number {
        return this._userID;
    }

    //#endregion userID 

    //#region ipAddress

    @observable private _ipAddress: string = null;

    @TypeSystem.propertyDecorator('string')
    public set ipAddress(val: string) {
        this._ipAddress = val;
    }

    public get ipAddress(): string {
        return this._ipAddress;
    }

    //#endregion ipAddress 

    //#region additionalData

    @observable private _additionalData: any = null;

    @TypeSystem.propertyDecorator('any')
    public set additionalData(val: any) {
        this._additionalData = val;
    }

    public get additionalData(): any {
        return this._additionalData;
    }

    //#endregion additionalData 

    //#region userEmail

    @observable private _userEmail: string = null;

    @TypeSystem.propertyDecorator('string')
    public set userEmail(val: string) {
        this._userEmail = val;
    }

    public get userEmail(): string {
        return this._userEmail;
    }

    //#endregion userEmail 

    constructor(obj?: any) {
        super(obj)

        this.copyFrom(obj);
    }
} 