import { BaseProps, ViewMode } from "cnsys-ui-react";
import { attributesClassFormControlRequiredLabel, Constants, EAUBaseComponent } from "eau-core";
import { AISCaseURIUI, DocumentURIUI, EkatteAddressUI, ElectronicServiceApplicantUI, ElectronicServiceProviderBasicDataUI, FieldFormUI } from "eau-documents";
import React from "react";
import { NotificationForTemporaryRegistrationPlatesVM } from "../../models/ModelsAutoGenerated";
import { attributesClassFormControlLabel } from "../field-forms/MerchantDataCompanyCaseUI";

export class NotificationForTemporaryRegistrationPlatesUI extends EAUBaseComponent<BaseProps, NotificationForTemporaryRegistrationPlatesVM> {

    renderEdit(): JSX.Element {
        return (
            <>
                {
                    this.model.documentURI && <div className="row">
                        <div className="form-group col-12">
                            <p className="page-subtitle">
                                {this.getResource("GL_URI_L")} <DocumentURIUI {...this.bind(m => m.documentURI)} />
                            </p>
                            {
                                this.model.documentReceiptOrSigningDate && <p className="page-date">{this.getResource("GL_DATE_L")} {this.dateDisplayFor(this.model.documentReceiptOrSigningDate, Constants.DATE_FORMATS.date)}</p>
                            }
                        </div>
                    </div>
                }
                <FieldFormUI title={this.getResource("GL_ElectronicServiceProviderBasicData_L")}>
                    <ElectronicServiceProviderBasicDataUI {...this.bind(m => m.electronicServiceProviderBasicData)} />
                </FieldFormUI>
                <ElectronicServiceApplicantUI {...this.bind(m => m.electronicServiceApplicant)} viewMode={ViewMode.Display} />
                <FieldFormUI title={this.getResourceByProperty(m => m.entityManagementAddress)}>
                    <div className="row">
                        <div className="form-group col-12">
                            <EkatteAddressUI {...this.bind(m => m.entityManagementAddress)} viewMode={ViewMode.Display} />
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResource("DOC_GL_CasefileData_L")}>
                    <div className="row">
                        <div className="form-group col-12">
                            <h4 className="form-control-label">{this.getResource("GL_URI_CASE_L")}</h4>
                            <p className="field-text"><AISCaseURIUI {...this.bind(m => m.aisCaseURI)} /></p>
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResource("DOC_KAT_COUNT_OF_SETS_OF_TEMPORARY_PLATES_TITLE_L")}>
                    <div className="row">
                        <div className="form-group col-sm-4 col-lg-3">
                            {this.labelFor(x => x.countOfSetsOfTemporaryPlates, null, attributesClassFormControlRequiredLabel)}
                            {this.textBoxFor(x => x.countOfSetsOfTemporaryPlates)}
                        </div>
                        <div className="form-group col-sm-4 col-lg-3">
                            {this.labelFor(x => x.countOfSetsOfTemporaryPlatesText, null, attributesClassFormControlRequiredLabel)}
                            {this.textBoxFor(x => x.countOfSetsOfTemporaryPlatesText)}
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResourceByProperty(x => x.registrationNumbersForEachSet)} required>
                    <div className="row">
                        <div className="form-group col-12">
                            {this.textAreaFor(x => x.registrationNumbersForEachSet)}
                            {this.inlineHelpFor(x => x.registrationNumbersForEachSet, "DOC_KAT_REGISTRATION_NUMBERS_FOR_EACH_SET_INFO_L")}
                        </div>
                    </div>
                </FieldFormUI>
            </>
        )
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                {
                    this.model.documentURI && <div className="row">
                        <div className="form-group col-12">
                            <p className="page-subtitle">
                                {this.getResource("GL_URI_L")} <DocumentURIUI {...this.bind(m => m.documentURI)} />
                            </p>
                            {this.model.documentReceiptOrSigningDate && <p className="page-date">{this.getResource("GL_DATE_L")} {this.dateDisplayFor(this.model.documentReceiptOrSigningDate, Constants.DATE_FORMATS.date)}</p>}
                        </div>
                    </div>
                }
                <FieldFormUI title={this.getResource("GL_ElectronicServiceProviderBasicData_L")}>
                    <ElectronicServiceProviderBasicDataUI {...this.bind(m => m.electronicServiceProviderBasicData)} />
                </FieldFormUI>
                <ElectronicServiceApplicantUI {...this.bind(m => m.electronicServiceApplicant)} viewMode={ViewMode.Display} />
                <FieldFormUI title={this.getResourceByProperty(m => m.entityManagementAddress)}>
                    <div className="row">
                        <div className="form-group col-12">
                            <EkatteAddressUI {...this.bind(m => m.entityManagementAddress)} viewMode={ViewMode.Display} />
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResource("DOC_GL_CasefileData_L")}>
                    <div className="row">
                        <div className="form-group col-12">
                            <h4 className="form-control-label">{this.getResource("GL_URI_CASE_L")}</h4>
                            <p className="field-text"><AISCaseURIUI {...this.bind(m => m.aisCaseURI)} /></p>
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResource("DOC_KAT_COUNT_OF_SETS_OF_TEMPORARY_PLATES_TITLE_L")}>
                    <div className="row">
                        <div className="form-group col-sm-4 col-lg-3">
                            {this.labelFor(x => x.countOfSetsOfTemporaryPlates, null, attributesClassFormControlLabel)}
                            {this.textDisplayFor(x => x.countOfSetsOfTemporaryPlates)}
                        </div>
                        <div className="form-group col-sm-4 col-lg-3">
                            {this.labelFor(x => x.countOfSetsOfTemporaryPlatesText, null, attributesClassFormControlLabel)}
                            {this.textDisplayFor(x => x.countOfSetsOfTemporaryPlatesText)}
                        </div>
                    </div>
                </FieldFormUI>
                <FieldFormUI title={this.getResourceByProperty(x => x.registrationNumbersForEachSet)}>
                    <div className="row">
                        <div className="form-group col-12">
                            {this.textDisplayFor(x => x.registrationNumbersForEachSet)}
                        </div>
                    </div>
                </FieldFormUI>
            </>
        )
    }
}