import { BaseProps } from "cnsys-ui-react";
import { Constants, EAUBaseComponent, resourceManager } from "eau-core";
import { DocumentURIUI, FieldFormUI } from "eau-documents";
import React from "react";
import { ReportForVehicleVM } from "../../models/ModelsAutoGenerated";
import { EucarisDataUI } from "../field-forms/EucarisDataUI";
import { GuaranteeFundUI } from "../field-forms/GuaranteeFundUI";
import { PeriodicTechnicalCheckUI } from "../field-forms/PeriodicTechnicalCheckUI";
import { ReportForVehicleOwnersUI } from "../field-forms/ReportForVehicleOwnersUI";
import { ReportForVehicleRPSSVehicleDataUI } from "../field-forms/ReportForVehicleRPSSVehicleDataUI";

export class ReportForVehicleUI extends EAUBaseComponent<BaseProps, ReportForVehicleVM> {

    render(): JSX.Element {
        return (
            <>
                <div className="row">
                    <div className="form-group col-12">
                        <p className="page-subtitle">
                            {this.getResource("GL_URI_L")} <DocumentURIUI {...this.bind(m => m.documentURI)} />
                        </p>
                        <p className="page-date">{this.getResource("GL_DATE_L")} {this.dateDisplayFor(this.model.documentReceiptOrSigningDate, Constants.DATE_FORMATS.date)}</p>
                    </div>
                </div>
                <section className="interactive-container" aria-labelledby="SECTION-TITLE-1">
                    <div className="interactive-container__content">
                        <h2 className="section-title" id="SECTION-TITLE-1">{resourceManager.getResourceByKey('DOC_KAT_REPORT_DATA_PPS_L')}</h2>
                        {
                            this.model.rpssVehicleData && <FieldFormUI title={this.getResourceByProperty(x => x.rpssVehicleData)}>
                                <ReportForVehicleRPSSVehicleDataUI {...this.bind(x => x.rpssVehicleData)} />
                            </FieldFormUI>
                        }
                        {
                            this.model.eucarisData && <EucarisDataUI {...this.bind(m => m.eucarisData)} />
                        }
                        {
                            this.model.guaranteeFund && <FieldFormUI title={this.getResourceByProperty(m => m.guaranteeFund)}>
                                <GuaranteeFundUI {...this.bind(m => m.guaranteeFund)} />
                            </FieldFormUI>
                        }
                        {
                            this.model.periodicTechnicalCheck && <FieldFormUI title={this.getResourceByProperty(m => m.periodicTechnicalCheck)}>
                                <PeriodicTechnicalCheckUI {...this.bind(m => m.periodicTechnicalCheck)} />
                            </FieldFormUI>
                        }
                    </div>
                </section>
                <section className="interactive-container" aria-labelledby="SECTION-TITLE-2">
                    <div className="interactive-container__content">
                        <h2 className="section-title" id="SECTION-TITLE-2">{this.getResourceByProperty(x => x.owners)}</h2>
                        <ReportForVehicleOwnersUI {...this.bind(x => x.owners)} />
                    </div>
                </section>
            </>
        )
    }
}