import { ItemCacheBase } from 'cnsys-core';
import { ObjectType } from '../models/ModelsAutoGenerated';
import { OjectTypesDataService } from '../services/OjectTypesDataService';

export class ObjectTypesDataCache extends ItemCacheBase<ObjectType[]> {

    protected generateValue(key: string): Promise<ObjectType[]> {

        let dataService = new OjectTypesDataService();

        return dataService.getOjectTypes();
    }
}