import { EAUBaseValidator } from "eau-core";
import { DeclarationsVMValidator, DocumentFormValidationContext, ElectronicServiceApplicantVMValidator, ServiceTermTypeAndApplicantReceiptVMValidator } from "eau-documents";
import { NotificationForConcludingOrTerminatingEmploymentContractVM } from "../../models/ModelsAutoGenerated";
import { NotificationForConcludingOrTerminatingEmploymentContractDataValidator } from "../NotificationForConcludingOrTerminatingEmploymentContractDataValidator";


export class NotificationForConcludingOrTerminatingEmploymentContractValidator
    extends EAUBaseValidator<NotificationForConcludingOrTerminatingEmploymentContractVM, DocumentFormValidationContext> {
    constructor() {
        super();

        this.ruleFor(m => m.electronicServiceApplicant).setValidator(new ElectronicServiceApplicantVMValidator());
        this.ruleFor(m => m.circumstances).setValidator(new NotificationForConcludingOrTerminatingEmploymentContractDataValidator());
        this.ruleFor(m => m.declarations).setValidator(new DeclarationsVMValidator());
        this.ruleFor(m => m.serviceTermTypeAndApplicantReceipt).setValidator(new ServiceTermTypeAndApplicantReceiptVMValidator());
    }
}