import { ArrayHelper, ObjectHelper } from "cnsys-core";
import { resourceManager } from "eau-core";
import React from "react";
import { Status } from "../../models/ModelsAutoGenerated";

interface DisplayStatusesProps {
    statuses: Status[];
    warningLabel?: string;
}

export const DisplayStatusesUI: React.FC<DisplayStatusesProps> = ({ statuses, warningLabel }) => {

    if (!ObjectHelper.isNullOrUndefined(statuses) && statuses.length > 0) {

        const warnings = ArrayHelper.queryable.from(statuses).where(el => el.blocking == false).toArray();
        const errors = ArrayHelper.queryable.from(statuses).where(el => el.blocking == true).toArray();

        return <>
            {
                warnings && warnings.length > 0 && <div className="alert alert-warning" role="alert">
                    {warningLabel ? <b>{warningLabel}</b> : null}
                    {warnings.map((warning, index) => <p key={index}>{warning.description}</p>)}
                </div>
            }
            {
                errors && errors.length > 0 && <div className="alert alert-danger" role="alert">
                    <b>{resourceManager.getResourceByKey("GL_SERVICE_TERMINATION_E")}</b>
                    {errors.map((error, index) => <p key={index} >{error.description}</p>)}
                </div>
            }
        </>
    }

    return null;
}

interface DisplayStatusProps {
    status: Status;
}

export const DisplayStatusUI: React.FC<DisplayStatusProps> = ({ status }) => {

    if (status) {

        return <div className="row">
            <div className="form-group col-12">
                {
                    status.blocking == true
                        ? <div className="alert alert-danger" role="alert">
                            <b>{resourceManager.getResourceByKey("GL_SERVICE_TERMINATION_E")}</b>
                            <p className="field-text">{status.description}</p>
                        </div>
                        : <div className="alert alert-warning" role="alert">
                            <p className="field-text">{status.description}</p>
                        </div>
                }
            </div>
        </div>
    }

    return null;
}