import React from "react";
import { action } from 'mobx';
import { observer } from "mobx-react";
import { SelectListItem, ObjectHelper } from "cnsys-core";
import { BaseProps } from "cnsys-ui-react";
import { attributesClassFormControlReqired, attributesClassFormControlRequiredLabel, EAUBaseComponent } from "eau-core";
import { PersonIdentifier, PersonIdentifierChoiceType } from "eau-documents";
import { InitialVehicleRegistrationUserOrOwnerOfSRMPSVM, PersonEntityChoiceType } from "../../models/ModelsAutoGenerated";
import { PersonIdentifierKATUI } from "./PersonIdentifierKATUI";
import { withApplicationForInitialVehicleRegistrationDataContext } from "../section-forms/withApplicationForInitialVehicleRegistrationDataContex";
import { IApplicationForInitialVehicleRegistrationDataContextProps } from "../section-forms/ApplicationForInitialVehicleRegistrationDataUI"

interface InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUProps extends BaseProps, IApplicationForInitialVehicleRegistrationDataContextProps {
}

@observer class InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUIImpl extends EAUBaseComponent<InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUProps, InitialVehicleRegistrationUserOrOwnerOfSRMPSVM> {
    private peronEntityChoiceTypes: SelectListItem[];
    private cbVehicleRepresentativeId: string;

    constructor(props?: InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUProps, context?: any) {
        super(props, context);

        //Bind
        this.onOwnerTypeChange = this.onOwnerTypeChange.bind(this);
        this.onVehicleRepresentativeChange = this.onVehicleRepresentativeChange.bind(this);

        //Init
        this.cbVehicleRepresentativeId = ObjectHelper.newGuid();
        this.peronEntityChoiceTypes = [
            new SelectListItem({
                value: PersonEntityChoiceType.Person.toString(),
                text: this.getResource("DOC_GL_PersonAndEntityChoiceType_Person_L"),
                selected: this.model.type === PersonEntityChoiceType.Person
            }),
            new SelectListItem({
                value: PersonEntityChoiceType.Entity.toString(),
                text: this.getResource("DOC_KAT_LEGAL_ENTITY_OR_AGRICULTURAL_PRODUCER_L"),
                selected: this.model.type === PersonEntityChoiceType.Entity
            })
        ];
    }

    renderEdit(): JSX.Element {
        return (
            <>
                <div className="row">
                    <div className="form-group col-12">
                        <fieldset>
                            <legend className="form-control-label">{this.getResourceByProperty(m => m.type)}</legend>
                            {this.radioButtonListFor(m => m.type, this.peronEntityChoiceTypes, null, this.onOwnerTypeChange)}
                        </fieldset>
                    </div>
                </div>
                {this.model.type == PersonEntityChoiceType.Person ?
                    <PersonIdentifierKATUI {...this.bind(m => m.personIdentifier)} />
                    :
                    <div className="row">
                        <div className="col-12">
                            {this.labelFor(m => m.entityIdentifier, null, attributesClassFormControlRequiredLabel)}
                        </div>
                        <div className="form-group col col-sm-6">
                            {this.textBoxFor(m => m.entityIdentifier, attributesClassFormControlReqired)}
                        </div>
                    </div>}
                <div className="row">
                    <div className="form-group col-12">
                        {this.model.type == PersonEntityChoiceType.Person &&
                            <div className="custom-control custom-checkbox">
                                <input
                                    id={this.cbVehicleRepresentativeId}
                                    type="checkbox"
                                    name={this.cbVehicleRepresentativeId}
                                    className="custom-control-input"
                                    value={this.model.isVehicleRepresentative === true ? 1 : 0}
                                    checked={this.model.isVehicleRepresentative === true}
                                    onChange={this.onVehicleRepresentativeChange}
                                    disabled={(this.props.isVehicleRepresentativeChoosen() === true && (ObjectHelper.isNullOrUndefined(this.model.isVehicleRepresentative) || this.model.isVehicleRepresentative === false))} />
                                <label htmlFor={this.cbVehicleRepresentativeId} className="custom-control-label">
                                    {this.getResourceByProperty(m => m.isVehicleRepresentative)}
                                </label>
                            </div>}
                    </div>
                </div>
            </>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <>
                <div className="row">
                    <div className="form-group col-12">
                        {/** Вид на лицето */}
                        <h4 className="form-control-label">{this.getResourceByProperty(m => m.type)}</h4>
                        <p className="field-text">
                            {this.model.type == PersonEntityChoiceType.Person && this.getResource("DOC_GL_PersonAndEntityChoiceType_Person_L")}
                            {this.model.type == PersonEntityChoiceType.Entity && this.getResource("DOC_KAT_LEGAL_ENTITY_OR_AGRICULTURAL_PRODUCER_L")}
                        </p>
                        {this.propertyErrorsDispleyFor(m => m.type)}
                    </div>
                </div>
                {this.model.type == PersonEntityChoiceType.Person ?
                    <PersonIdentifierKATUI {...this.bind(m => m.personIdentifier)} />
                    :
                    <div className="row">
                        <div className="form-group col-6">
                            <h4 className="form-control-label">{this.getResourceByProperty(x => x.entityIdentifier)}</h4>
                            {this.textDisplayFor(m => m.entityIdentifier)}
                        </div>
                    </div>}
                <div className="row">
                    {this.model.type == PersonEntityChoiceType.Person && this.model.isVehicleRepresentative === true &&
                        <div className="form-group col-12">
                            <p className="field-text check-item check-success">
                                {this.getResourceByProperty(m => m.isVehicleRepresentative)}
                            </p>
                        </div>}
                </div>
            </>
        );
    }

    @action onOwnerTypeChange(e: any): void {
        let val: PersonEntityChoiceType = Number(e.target.value);

        if (val == PersonEntityChoiceType.Person) {
            this.model.type = PersonEntityChoiceType.Person;
            this.model.entityIdentifier = undefined;
            this.model.personIdentifier = new PersonIdentifier();
            this.model.personIdentifier.itemElementName = PersonIdentifierChoiceType.EGN;
        } else {
            this.model.type = PersonEntityChoiceType.Entity;
            this.model.personIdentifier = undefined;
            this.model.entityIdentifier = undefined;
        }

        this.model.isVehicleRepresentative = false;
    }

    @action private onVehicleRepresentativeChange(e: any): void {
        this.model.isVehicleRepresentative = e.target.value == "0" ? true : false;
    }
}

export const InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUI = withApplicationForInitialVehicleRegistrationDataContext(InitialVehicleRegistrationUserOrOwnerOfSRMPSVMUIImpl);