import React from "react";
import { observer } from "mobx-react";
import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent } from "eau-core";
import { MerchantDataCompanyCase } from "../../models/ModelsAutoGenerated";

interface MerchantDataCompanyCaseUIProps extends BaseProps {
}

export const attributesClassFormControlLabel = { className: 'form-control-label' };

@observer export class MerchantDataCompanyCaseUI extends EAUBaseComponent<MerchantDataCompanyCaseUIProps, MerchantDataCompanyCase> {
    renderEdit(): JSX.Element {
        return (
            <div className="row">
                <div className="form-group col-sm-6">
                    {/** Номер */}
                    {this.labelFor(m => m.number, null, attributesClassFormControlLabel)}
                    {this.textBoxFor(m => m.number)}
                </div>
                <div className="form-group col-sm-6">
                    {/** Съд по регистрация */}
                    {this.labelFor(m => m.courtName, null, attributesClassFormControlLabel)}
                    {this.textBoxFor(m => m.courtName)}
                </div>
            </div>
        );
    }

    renderDisplay(): JSX.Element {
        return (
            <div className="row">
                <div className="form-group col-sm-6">
                    {/** Номер */}
                    {this.labelFor(m => m.number, null, attributesClassFormControlLabel)}
                    {this.textDisplayFor(m => m.number)}
                </div>
                <div className="form-group col-sm-6">
                    {/** Съд по регистрация */}
                    {this.labelFor(m => m.courtName, null, attributesClassFormControlLabel)}
                    {this.textDisplayFor(m => m.courtName)}
                </div>
            </div>
        );
    }
}