import { BaseProps } from "cnsys-ui-react";
import { EAUBaseComponent } from "eau-core";
import { FieldFormUI } from "eau-documents";
import React from "react";
import { ReportForVehicleRPSSVehicleDataVM } from "../../models/ModelsAutoGenerated";
import { DisplayStatusesUI } from "./DisplayStatusesUI";
import { ReportForVehicleRPSSVehicleDataOwnersUI } from "./ReportForVehicleRPSSVehicleDataOwnersUI";
import { VehicleRegistrationDataForDocs2UI } from "./VehicleRegistrationDataForDocs2UI";

interface ReportForVehicleRPSSVehicleDataProps extends BaseProps {
}

export class ReportForVehicleRPSSVehicleDataUI extends EAUBaseComponent<ReportForVehicleRPSSVehicleDataProps, ReportForVehicleRPSSVehicleDataVM> {

    render(): JSX.Element {
        return (
            <>
                <VehicleRegistrationDataForDocs2UI {...this.bind(m => m.vehicleRegistrationData)} />
                <FieldFormUI headerType={"h4"} title={this.getResourceByProperty(x => x.owners)}>
                    <ul className="list-filed">
                        {
                            this.model.owners && this.model.owners.map((owner, index) => {
                                return <li role="group" className="list-filed__item" aria-label={`${this.getResource("GL_Owner_L")} ${index + 1}`} key={index}>
                                    <ReportForVehicleRPSSVehicleDataOwnersUI {...this.bindArrayElement(x => x.owners[index], [index])} />
                                </li >
                            })
                        }
                    </ul>
                </FieldFormUI>
                <DisplayStatusesUI statuses={this.model.statuses} />
            </>
        );
    }
}