import { ObjectHelper } from "cnsys-core";
import { BaseProps, ViewMode } from "cnsys-ui-react";
import { EAUBaseComponent } from "eau-core";
import { GraoAddressUI, PersonIdentifierUI, PersonNamesUI } from "eau-documents";
import React from "react";
import { EntityDataVM, PersonDataVM, ReportForVehicleRPSSVehicleDataOwnersVM } from "../../models/ModelsAutoGenerated";
import { DisplayStatusUI } from "./DisplayStatusesUI";

export class ReportForVehicleRPSSVehicleDataOwnersUI extends EAUBaseComponent<BaseProps, ReportForVehicleRPSSVehicleDataOwnersVM>{

    render(): JSX.Element {

        if (!ObjectHelper.isNullOrUndefined(this.model.personData))
            return <ReportForVehicleRPSSVehicleDataPersonOwner {...this.bind(x => x.personData)} />
        else if (!ObjectHelper.isNullOrUndefined(this.model.entityData))
            return <ReportForVehicleRPSSVehicleDataEntityOwner {...this.bind(x => x.entityData)} />

        return null;
    }
}

export class ReportForVehicleRPSSVehicleDataPersonOwner extends EAUBaseComponent<BaseProps, PersonDataVM>{
    render() {
        return <>
            <div className="row">
                <PersonNamesUI {...this.bind(x => x.names)} viewMode={ViewMode.Display} />
                <PersonIdentifierUI {...this.bind(x => x.identifier)} viewMode={ViewMode.Display} />
            </div>
            <div className="row">
                <div className="form-group col-12">
                    <h4 className="form-control-label">{this.getResource('DOC_GL_PersonAddress_L')}</h4>
                    <GraoAddressUI {...this.bind(x => x.permanentAddress)} viewMode={ViewMode.Display} />
                </div>
            </div>
            <DisplayStatusUI status={this.model.status} />
        </>
    }
}

export class ReportForVehicleRPSSVehicleDataEntityOwner extends EAUBaseComponent<BaseProps, EntityDataVM>{
    render() {
        return <>
            <div className="row">
                <div className="form-group col-12">
                    <h4 className="form-control-label">{this.getResource("DOC_KAT_reportForVehicle_entityData_name_L")}</h4>
                    {this.textDisplayFor(m => m.name)}
                </div>
                <div className="form-group col-sm-6">
                    <h4 className="form-control-label">{this.getResourceByProperty(m => m.identifier)}</h4>
                    {this.textDisplayFor(m => m.identifier)}
                </div>
            </div>
            <div className="row">
                <div className="form-group col-12">
                    <h4 className="form-control-label">{this.getResourceByProperty(m => m.entityManagmentAddress)}</h4>
                    <GraoAddressUI {...this.bind(x => x.entityManagmentAddress)} viewMode={ViewMode.Display} />
                </div>
            </div>
            <DisplayStatusUI status={this.model.status} />
        </>
    }
}