INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (1, 43621, 1, N'GL_ITEMS_PER_PAGE', N'Брой елементи на страница.', 0, 4, NULL, NULL, NULL, 10, NULL, 1, NULL, 227, CAST(N'2020-08-11T18:01:03.2000000+03:00' AS DateTimeOffset), 227, CAST(N'2020-08-11T18:01:03.2000000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (13, 53687, 1, N'EML_MAX_EMAILS_FETCHED', N'Максимален брой съобщения, които могат да бъдат взети при една итерация.', 0, 4, NULL, NULL, NULL, 100, NULL, 1, NULL, 240, CAST(N'2020-08-12T17:00:53.7100000+03:00' AS DateTimeOffset), 240, CAST(N'2020-08-12T17:00:53.7100000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (14, 53688, 1, N'EML_POLLING_INTERVAL', N'Период от време, през който се изпращат неизпратените имейл съобщения.', 0, 2, NULL, CAST(N'1900-01-01T00:00:03.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 240, CAST(N'2020-08-12T17:01:01.7890000+03:00' AS DateTimeOffset), 240, CAST(N'2020-08-12T17:01:01.7890000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (15, 43024, 1, N'EML_SEND_FROM', N'Имейл адрес, от който се пращат съобщенията.', 0, 3, NULL, NULL, N'mailsender@dev.local', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:47:47.2130000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:47:47.2130000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (16, 776, 1, N'EML_SMTP_HOST', N'Адрес на SMTP сървър за изпращане на имейл съобщения.', 0, 3, NULL, NULL, N'devmail.dev.local', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-11T17:16:45.5360000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-11T17:16:45.5360000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (17, 43018, 1, N'EML_SMTP_PASSWORD', N'Парола на потребител за достъп до SMTP сървър.', 0, 3, NULL, NULL, N'R1r2r3r4', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:43:17.2900000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:43:17.2900000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (18, 43013, 1, N'EML_SMTP_USER', N'Потребител за достъп до SMTP сървър.', 0, 3, NULL, NULL, N'dev\mailsender', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:40:54.7530000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:40:54.7530000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (19, 53689, 1, N'EML_SMTP_PORT', N'Порт на SMTP сървър за изпращане на имейл съобщения.', 0, 4, NULL, NULL, NULL, 25, NULL, 1, NULL, 240, CAST(N'2020-08-12T17:01:10.9110000+03:00' AS DateTimeOffset), 240, CAST(N'2020-08-12T17:01:10.9110000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (20, 10836, 1, N'GL_IDSRV_URL', N'Адрес на сървъра за идентичност', 0, 3, NULL, NULL, N'https://login-e-uslugi.dev.mvr-eau.dev.local', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-16T08:45:19.4040000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-16T08:45:19.4040000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (21, 10834, 1, N'GL_EAU_PUBLIC_APP', N'Публичен адрес на портала', 0, 3, NULL, NULL, N'https://e-uslugi.qa.mvr-eau.dev.local/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-16T08:44:05.9240000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-16T08:44:05.9240000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (22, 42473, 1, N'IDSRV_SIGN_CERT_THUMBPRINT', N'Thumbprint на сертификата, чрез който се подписват издадените token - и от сървъра за идентичност. Сертификатът трябва да бъде инсталиран в локалното хранилище за сертификати на всяка машина, на която работи услугата.', 0, 3, NULL, NULL, N'bf1f8d72f433639a3d557d8dae3dc931577a1bba', NULL, NULL, 1, NULL, 101, CAST(N'2020-07-14T15:36:15.5920000+03:00' AS DateTimeOffset), 101, CAST(N'2020-07-14T15:36:15.5920000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (23, 10838, 1, N'IDSRV_CONFIG_DB_CONNECTION_STRING', N'Връзка към базата данни на Admin-a на Идентити сървъра. Трябва да бъде във формат за SqlServer драйвър.', 0, 3, NULL, NULL, N'Data Source=vm-mvr-eau-db.dev.local;Initial Catalog=EAU_IDSRV_DEV;Persist Security Info=True;User ID=eau_idsrv_owner;Password=eau_idsrv_owner', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-16T09:06:09.9050000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-16T09:06:09.9050000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (24, 11130, 3, N'SIGN_ALLOW_TEST_SIGN', N'Позволява тестово подписване на заявления и прикачени документи към тях (показва - 1/скрива - 0 бутона за тестово подписване) със сървърния сертификат, който се ползва при криптиране на комуникацията с BISS.', 0, 4, NULL, NULL, NULL, 1, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:09:24.3750000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:09:24.3750000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (25, 11131, 3, N'SIGN_BISS_CERT_THUMBPRINT', N'Тhumbprint на сървърен сертификат за криптиране на комуникацията между ЕАУ и BISS - локална услуга за подписване в браузер.', 0, 3, NULL, NULL, N'a30bd361b176e3b227d487e9e75e6fc68840ea37', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:18:32.1650000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:18:32.1650000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (26, 11132, 3, N'SIGN_BSECURE_DSSL_API', N'Базов адрес за достъп до услугата BSecure DSSL на B-Trust.', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-eau.dev.local/Services/bsecureDSSL/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:20:35.8870000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:20:35.8870000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (27, 11133, 3, N'SIGN_BTRUST_REMOTE_CLIENT_API', N'Базов адрес за достъп до услугата за отдалечено подписване на B-Trust.', 0, 3, NULL, NULL, N'https://cqes-rptest.b-trust.bg/signing-api/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:21:24.0490000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:21:24.0490000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (28, 11134, 3, N'SIGN_BTRUST_REMOTE_CLIENT_CERT', N'Сертификат за ауторизация пред услугата за отдалечено подписване на B-Trust.', 0, 3, NULL, NULL, N'2d545b381b3b23b60b0118561f0d88706a12dbc6', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:22:23.0620000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:22:23.0620000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (29, 11135, 3, N'SIGN_BTRUST_REMOTE_RELYINGPARTY_ID', N'Идентификатор на електронен портал на СППТЕАУ на B-Trust.', 0, 3, NULL, NULL, N'683453248', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:23:43.9930000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:23:43.9930000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (30, 11136, 3, N'SIGN_EVROTRUST_CALLBACK_BASE_URL', N'Базов адрес, на който Evrotrust да извести за промяна в статуса на документ за подписване.', 0, 3, NULL, NULL, N'https://reverse-proxy.cnsys.bg/EPZEU_PR900293/dev/api/api/EvrotrustCallback/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:24:51.9440000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:24:51.9440000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (31, 11137, 3, N'SIGN_EVROTRUST_CLIENT_API', N'Базов адрес за достъп до услугата за отдалечено подписване на Evrotrust.', 0, 3, NULL, NULL, N'https://v.evrotrust.com/vendor/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:27:31.5050000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:27:31.5050000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (32, 11138, 3, N'SIGN_EVROTRUST_VENDOR_API_KEY', N'Ключ за ауторизация пред услугата за отдалечено подписване на Evrotrust.', 0, 3, NULL, NULL, N'9f7295da-41cc-44c5-a3c6-fd3d3da712d8', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:29:20.1300000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:29:20.1300000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (33, 11139, 3, N'SIGN_EVROTRUST_VENDOR_NUM', N'Номер на продавача (публичната част на ЕАУ МВР) в системата на Evrotrust.', 0, 3, NULL, NULL, N'D8kMmEpPV5sh6QYA', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:30:29.4060000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:30:29.4060000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (34, 11140, 3, N'SIGN_SIGNATURE_LEVEL', N'Конфигурира какво ниво на подпис да използва модула за подписване.Възможни стойности: BASELINE_B, BASELINE_T, BASELINE_LT и BASELINE_LTA', 0, 3, NULL, NULL, N'BASELINE_LT', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:31:08.8760000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:31:08.8760000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (35, 11141, 3, N'SIGN_SKIP_VALIDATION_AFTER_SIGN', N'Конфигурира какво ниво на подпис да използва модула за подписване.Възможни стойности: BASELINE_B, BASELINE_T, BASELINE_LT и BASELINE_LTA', 0, 4, NULL, NULL, NULL, 0, NULL, 1, NULL, 1, CAST(N'2020-06-18T12:31:48.0070000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-18T12:31:48.0070000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (36, 11181, 1, N'GL_VERSION', N'Версия на системата', 0, 3, NULL, NULL, N'0.0.2', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-19T14:59:42.6060000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-19T14:59:42.6060000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (37, 11304, 1, N'GL_DOCUMENT_ALLOWED_FORMATS', N'Допустими типове файлове с документи, които могат да се прикачват.', 0, 3, NULL, NULL, N'[{ "extension": "docx", "mimeTypes": ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"], "hasMagicNumber": true }, { "extension": "doc", "mimeTypes": ["application/msword"], "hasMagicNumber": true }, { "extension": "rtf", "mimeTypes": ["application/rtf", "application/x-rtf"], "hasMagicNumber": true }, { "extension": "txt", "mimeTypes": ["text/plain"], "hasMagicNumber": false }, { "extension": "pdf", "mimeTypes": ["application/pdf", "application/x-pdf"], "hasMagicNumber": true }, { "extension": "jpg", "mimeTypes": ["image/jpeg", "image/pjpeg"], "hasMagicNumber": true }, { "extension": "jpeg", "mimeTypes": ["image/jpeg", "image/pjpeg"], "hasMagicNumber": true }, { "extension": "png", "mimeTypes": ["image/png"], "hasMagicNumber": true }, { "extension": "gif", "mimeTypes": ["image/gif"], "hasMagicNumber": true } , { "extension": "tiff", "mimeTypes": ["image/tiff", "image/x-tiff"], "hasMagicNumber": true }, { "extension": "p7s", "mimeTypes": ["application/pkcs7-signature", "application/x-pkcs7-signature", "application/keychain_access"], "hasMagicNumber": true }, { "extension": "sxw", "mimeTypes": ["application/vnd.sun.xml.writer"], "hasMagicNumber": true } ]', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-23T10:50:13.2260000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-23T10:50:13.2260000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (38, 11306, 1, N'GL_DOCUMENT_MAX_FILE_SIZE', N'Допустим размер на прикачен файл с документ в KB.', 0, 4, NULL, NULL, NULL, 10240, NULL, 1, NULL, 1, CAST(N'2020-06-23T11:22:16.8810000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-23T11:22:16.8810000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (39, 43081, 1, N'GL_APPLICATION_DRAFTS_AUTO_SAVE_INTERVAL', N'Интервал на запазване на черновата на заявлението.', 0, 2, NULL, CAST(N'1900-01-06T11:31:30.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 2, CAST(N'2020-07-30T11:28:41.1510000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-30T11:28:41.1510000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (40, 21479, 1, N'USR_LOCK_FOR_PERIOD', N'Период от време за изчакване преди да бъде автоматично отключен потребителския профил след определен брой неуспешни опити за автентикация.', 0, 2, NULL, CAST(N'1900-01-01T00:05:00.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 1, CAST(N'2020-06-30T13:36:47.2560000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-30T13:36:47.2560000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (41, 21482, 1, N'USR_MAX_LOGIN_ATTEMPT_COUNT', N'Максимален брой неуспешни опити за автентикация на потребител.', 0, 4, NULL, NULL, NULL, 5, NULL, 1, NULL, 1, CAST(N'2020-06-30T13:38:50.2010000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-30T13:38:50.2010000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (42, 21484, 1, N'GL_USR_PROCESS_CONFIRM_PERIOD', N'Период от време за изчакване на потвърждение от потребител при регистрация на профил на нов външен потребител.', 0, 2, NULL, CAST(N'1900-01-07T00:00:00.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 1, CAST(N'2020-06-30T13:40:38.1630000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-30T13:40:38.1630000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (57, 21569, 1, N'GL_USR_LDAP_USERNAME', N'Потребител за достъп до LDAP сървър.', 0, 3, NULL, NULL, N'Ldap-reader', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (58, 21570, 1, N'GL_USR_LDAP_PASSWORD', N'Парола на потребител за достъп до LDAP сървър.', 0, 3, NULL, NULL, N'r1r2r3r4', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (60, 21571, 1, N'GL_USR_LDAP_ACCOUNT_DOMAIN_NAME', N'Име на домейн за LDAP.', 0, 3, NULL, NULL, N'cnsys.plc', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (61, 21572, 1, N'GL_USR_LDAP_ACCOUNT_DOMAIN_NAME_SHORT', N'Кратко име на домейн за LDAP.', 0, 3, NULL, NULL, N'cnsys', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (62, 21574, 1, N'GL_USR_LDAP_HOST', N'Адрес на сървъра за активна директория.', 0, 3, NULL, NULL, N'LDAP://KIA.cnsys.plc', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (63, 21575, 1, N'GL_USR_LDAP_QUERY_REGEX', N'Регулярен израз за извличане на заявка за активна директория.', 0, 3, NULL, NULL, N'[^0-9a-zA-Zа-яА-Я ._-]', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (64, 21576, 1, N'GL_COPY_BUFFER_SIZE', N'Конфигурира размер на буфер за четене и писане.', 0, 4, NULL, NULL, NULL, 5120, NULL, 1, NULL, 1, CAST(N'2020-07-01T11:07:19.8890000+03:00' AS DateTimeOffset), 1, CAST(N'2020-07-01T11:07:19.8890000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (65, 21579, 1, N'GL_USR_LDAP_SURNAME_PATTERN', N'Шаблон за презиме от активна директория', 0, 3, NULL, NULL, N'secondName=*{0}*', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (66, 21580, 1, N'GL_USR_LDAP_LASTNAME_PATTERN', N'Шаблон за фамилия от активна директория', 0, 3, NULL, NULL, N'sn=*{0}*', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (67, 21582, 1, N'GL_USR_LDAP_USERNAME_PATTERN', N'Шаблон за потребителско име от активна директория', 0, 3, NULL, NULL, N'samaccountname=*{0}*', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (68, 21585, 1, N'GL_USR_LDAP_FILTER', N'Филтър за търсене в активна директория.', 0, 3, NULL, NULL, N'(&(CN=*)(objectclass=user)(objectcategory=person)', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (69, 21658, 1, N'GL_USR_LDAP_BASE_DN', N'Филтър за търсене в активна директория.', 0, 3, NULL, NULL, N'OU=Software department,OU=CNsys Users,DC=cnsys,DC=plc', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (70, 43011, 1, N'GL_ADM_STRUCTURE_NAME', N'Име на административна структура, предоставяща услугите', 0, 3, NULL, NULL, N'МИНИСТЕРСТВО НА ВЪТРЕШНИТЕ РАБОТИ', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:40:41.3570000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:40:41.3570000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (71, 43007, 1, N'GL_ADM_STRUCTURE_UIC', N'ЕИК на административна структура, предоставяща услугите', 0, 3, NULL, NULL, N'126608480', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:38:36.5050000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:38:36.5050000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (72, 43391, 2, N'GL_EAU_WAIS_INTEGRATION_API', N' Адрес на публично API на WAIS', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-peau.dev.local/Services/WAIS.Integration.EPortal.Service/api/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (73, 43402, 2, N'GL_EAU_PRIVATE_API', N' Адрес на публичното API на портала', 0, 3, NULL, NULL, N'https://e-uslugi.dev.mvr-eau.dev.local/api', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (75, 21577, 1, N'GL_USR_LDAP_FIRSTNAME_PATTERN', N'Шаблон за първо име от активна директория', 0, 3, NULL, NULL, N'givenName=*{0}*', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (76, 53693, 1, N'GL_ASPNETCORE_DP_KEY_CERT_THUMBPRINT', N'Thumbprint на сертификата, чрез който се криптират ключовете при съхранение в базата данни. При неналичие, ключовете се съхраняват в явен вид в базата данни. Сертификатът трябва да бъде инсталиран в локалното хранилище за сертификати на всяка машина, на която работи услугата.', 0, 3, NULL, NULL, N'bf1f8d72f433639a3d557d8dae3dc931577a1bba', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-12T17:26:07.5330000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-12T17:26:07.5330000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (77, 53700, 4, N'SERVICE_LIMIT_DOMAIN', N'Домейн в рамките на услугата за лимитиране.', 0, 3, NULL, NULL, N'eau_dev', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T10:53:32.4100000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T10:53:32.4100000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (78, 53701, 4, N'SERVICE_LIMIT_SERVER', N'Адрес на услуга за лимитиране. Пример: http://localhost:8081.', 0, 3, NULL, NULL, N'http://vm-mvr-lx-ap1.dev.local:8081', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T10:55:22.7800000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T10:55:22.7800000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (79, 53702, 4, N'SERVICE_LIMIT_DISABLED', N'Параметърът спира използването на услугата за лимитиране при стойност > 0. При стойност 0 се използва услугата за лимитиране.', 0, 4, NULL, 0, NULL, NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T10:56:33.1830000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T10:56:33.1830000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (80, 53703, 4, N'SERVICE_LIMIT_CFG_FILE', N'Път до конфигурационнен файл на сървъра за лимитиаране, където се съхранява конфигурацията за лимитиране.', 0, 3, NULL, NULL, N'/Lyft_Ratelimit/src/runtime/data2/ratelimit/config/eau_dev.yaml', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T10:58:48.3810000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T10:58:48.3810000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (81, 53704, 4, N'SERVICE_LIMIT_ON_SYNC_PROCESS', N'Процес, който се стартира след промяна на конфигурацията на услугата за лимитиране.', 0, 3, NULL, NULL, N'bash', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T10:59:17.8360000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T10:59:17.8360000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (82, 53705, 4, N'SERVICE_LIMIT_ON_SYNC_PROCESS_ARGS', N'Аргументи, които се подават на процеса, който се стартира след промяна на конфигурацията на услугата за лимитиране.', 0, 3, NULL, NULL, N'/Lyft_Ratelimit/src/runtime/reload-configuration.sh', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (83, 53754, 5, N'GL_AND_PEP_CIN', N'Идентификатор на клиент на ПЕП за плащане на задължения към АНД', 0, 3, NULL, NULL, N'ais_stru_91e4eb40-5871-4e58-8ca2-330948b845a3', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (84, 53754, 5, N'GL_MTLS_IDSRV_URL', N'Адрес на сървъра за идентичност - точка за вход със сертификат', 0, 3, NULL, NULL, N'https://mtls-login-e-uslugi.dev.mvr-eau.dev.local', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (85, 53754, 5, N'POSSIBLE_KAT_OBLIGATIONS_FISH_SERIES', N'Допустими видове серии за фиш', 0, 3, NULL, NULL, N'A,E,K,B,C,M,Г,Н', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (86, 53754, 5, N'AND_SERVICE_SUNAU_ID', N'Идентификатор на СУНАУ на услуга към АНД', 0, 3, NULL, NULL, N'100001', NULL, NULL, 1, NULL, 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset), 1, CAST(N'2020-08-13T11:00:03.5430000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (87, 63871, 1, 'GL_IDSRV_CERT_COOKIE_DOMAIN', N'Домейн за куки-то, в което временно се записва клиентския сертификат при вход с КЕП и регистриране на КЕП.', 0, 3, null, null, '.dev.mvr-eau.dev.local', null, null, 1, null,1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (88, 64178, 5, N'QUEUES_MAX_ATTEMPTS', N'Максимален брой опити за обработване на съобщение преди да се прехвърли към опашката със съобщения, които не могат да бъдат обработени.', 0, 4, NULL, NULL, NULL, 3, NULL, 1, NULL, 240, CAST(N'2020-09-03T17:49:20.6810000+03:00' AS DateTimeOffset), 240, CAST(N'2020-09-03T17:49:20.6810000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (89, 64179, 5, N'QUEUES_MAX_RETRY_INTERVAL', N'Максимален период за изчакване при последваща обработка на съобщение.', 0, 2, NULL, CAST(N'1900-01-01T00:00:30.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 240, CAST(N'2020-09-03T17:49:29.1110000+03:00' AS DateTimeOffset), 240, CAST(N'2020-09-03T17:49:29.1110000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (90, 64180, 5, N'QUEUES_RETRY_INTERVAL_INCREMENT', N'Стъпка, с която се увеличава периода за изчакване между отделните опити за обработка на съобщение.', 0, 2, NULL, CAST(N'1900-01-01T00:00:05.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 240, CAST(N'2020-09-03T17:49:37.9310000+03:00' AS DateTimeOffset), 240, CAST(N'2020-09-03T17:49:37.9310000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (91, 64232, 5, N'GL_WAIS_INTEGRATION_MOI_API', N'Адрес на WAIS.INTEGRATION.MOI.API', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-eau.dev.local/Services/Integrations/WAIS.Integration.MOI.Api/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10 12:07:11.861 +03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10 12:07:11.861 +03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (92, 74334, 1, N'GL_EAUTH_BASE_URL', N'Адрес на Е-Автентификация', 0, 3, NULL, NULL, N'https://eauth-test.egov.bg', NULL, NULL, 1, NULL, 1, CAST(N'2020-09-11 11:58:03.640 +03:00' AS DateTimeOffset), 1, CAST(N'2020-09-11 11:58:03.640 +03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (93, 74333, 5, N'GL_WAIS_INTEGRATION_NOTARY_API', N'Адрес на WAIS.INTEGRATION.NOTARY.API', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-eau.dev.local/Services/Integrations/WAIS.Integration.Notary.Api/', NULL, NULL, 1, NULL, 1, CAST(N'2020-09-24 11:58:03.640 +03:00' AS DateTimeOffset), 1, CAST(N'2020-09-24 11:58:03.640 +03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (94, 74334, 5, N'GL_SERVICE_INSTANCE_PAYMENT_REASON', N'Основание за плащане на задължение по услуга. Максимално 70 символа заедно с двете УРИ-та.', 0, 3, NULL, NULL, N'Плащане по док. {0} за усл. {1}', NULL, NULL, 1, NULL, 1, CAST(N'2020-09-30 11:58:03.640 +03:00' AS DateTimeOffset), 1, CAST(N'2020-09-30 11:58:03.640 +03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (95, 74930, 2, N'GL_EAU_USR_SESSION_INACTIVITY_INTERVAL', N'Разрешен интервал за неактивност от страна на потребителя.', 0, 2, NULL, CAST(N'1900-01-01T00:20:00.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (96, 96066, 5, N'GL_EAU_WAIS_NOMENCLATURES_API', N'Адрес на GL_EAU_WAIS_NOMENCLATURES_API', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-peau.dev.local/Services/WAIS.Integration.EPortal.Service/api/', NULL, NULL, 1, NULL, 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset), 1, CAST(N'2020-06-10T12:07:11.8610000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (97, 96189, 2, N'GL_CERT_SUBJ_PERSONIDENT_PATTERN', N'Патърн за извличане на идентификатор на лице от subject-a на сертификат', 0, 3, NULL, NULL, 'PNOBG-(?<value>\d{10}).*', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (98, 96190, 2, N'GL_CERT_SUBJ_UIC_PATTERN', N'Патърн за извличане на идентификатор на фирма от subject-a на сертификат', 0, 3, NULL, NULL, 'NTRBG-(?<value>\d{9}).*', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (99, 96191, 2, N'GL_CERT_SUBJ_PERSONNAMES_PATTERN', N'Патърн за извличане на имена на лице от subject-a на сертификат', 0, 3, NULL, NULL, N'CN\s*=\s*(?<value>[A-Za-zА-Яа-я0-9\s.,]*).*', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (100, 96192, 2, N'GL_CERT_SUBJ_PERSONLNCH_PATTERN', N'Патърн за извличане на идентификатор ЛНЧ от subject-a на сертификат', 0, 3, NULL, NULL, 'PI:BG-(?<value>\d+).', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (101, 96272, 5, N'GL_WAIS_INTEGRATION_REGIX_API', N'Адрес на GL_WAIS_INTEGRATION_REGIX_API', 0, 3, NULL, NULL, N'https://e-services.dev.mvr-eau.dev.local/Services/Integrations/WAIS.Integration.RegiX.Api/', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (102, 106693, 5, N'GL_APPLICATION_MAX_SIZE', N'Допустим размер на цялото заявление, включително приложените документи', 0, 4, NULL, NULL, NULL, 10240, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET())
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (103, 106922, 1, N'GL_POLLING_INTERVAL', N'Период на обноявяване на кеша.', 0, 2, NULL, CAST(N'1900-01-01T00:20:00.000' AS DateTime), NULL, NULL, NULL, 1, NULL, 1, CAST(N'2020-11-12T13:42:41.7410000+02:00' AS DateTimeOffset), 1, CAST(N'2020-11-12T13:42:41.7410000+02:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (104, 107382, 5, N'GL_IDSRV_EAUTH_CERT_THUMBPRINT', N'Thumbprint на сертификата с който идентити сървъра подписва комуникацията си с е-Авт', 0, 3, NULL, NULL, N'bf1f8d72f433639a3d557d8dae3dc931577a1bba', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (106, 107642, 5, N'GL_WEB_HELP_URL', N'Адрес на сайт за контекстна помощ.', 0, 3, NULL, NULL, N'https://help/index.html', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (107, 107645, 5, N'GL_WEB_HELP_CONFIG', N'JSON конфигурация за контекстната помощ.', 0, 3, NULL, NULL, N'[ 	{	"pattern": "/services/applicationProcesses/(?<serviceID>[0-9]+)/$",	"key": "applicationprocesses" 	}, {	"pattern": "/services/applicationProcesses/(?<serviceID>[0-9]+)/personalInformation$",	"key": "applicationprocesses_$1_personalInformation" 	}, {	"pattern": "/services/applicationProcesses/(?<serviceID>[0-9]+)/circumstances$",	"key": "applicationprocesses_$1_circumstances" 	}, {	"pattern": "/services/applicationProcesses/(?<serviceID>[0-9]+)/wayOfDelivery$",	"key": "applicationprocesses_$1_wayOfDelivery" 	}, {	"pattern": "/Account/Login(.*)",	"key": "login" 	} ]', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (108, 43011, 1, N'GL_ADM_STRUCTURE_NAME_SHORT', N'Кратко име на административна структура, предоставяща услугите. Не трябва да надвишава 25 символа, защото има такова ограничение за платежните портали.', 0, 3, NULL, NULL, N'МВР', NULL, NULL, 1, NULL, 2, CAST(N'2020-07-29T11:40:41.3570000+03:00' AS DateTimeOffset), 2, CAST(N'2020-07-29T11:40:41.3570000+03:00' AS DateTimeOffset))
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (109, @version, 5, N'GL_EGOV_EAUTH_CERT_THUMBPRINT', N'Thumbprint на сертификата на IdentityProvider-a на е-Авт. Сертификатът се взима от метадата адреса.', 0, 3, NULL, NULL, N'ffa29a50d5a76b41602c35a17b25056128bc0909', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO
INSERT [dbo].[app_parameters] ([app_param_id], [app_param_ver_id], [functionality_id], [code], [description], [is_system], [param_type], [value_datetime], [value_interval], [value_string], [value_int], [value_hour], [is_last], [deactivation_ver_id], [created_by], [created_on], [updated_by], [updated_on]) VALUES (110, 136228, 1, N'GL_EAU_ARCHIVE_DATABASE_NAME', N'Име на архивна база.', 1, 3, NULL, NULL, 'EAU_ARCHIVE_DEV', NULL, NULL, 1, NULL, 1, SYSDATETIMEOFFSET(), 1, SYSDATETIMEOFFSET());
GO